---
# Basic rulebook with an invalid job template, 
# to be used with https://github.com/Alex-Izquierdo/eda-awx-project-sample
- name: Basic short with an invalid job template name
  hosts: all
  sources:
    - name: generic
      ansible.eda.generic:
        create_index: i
        loop_count: 200000
        payload:
          - name: fred
  rules:
    - name: r1
      condition: event.name == "fred"
        timeout: 6 minutes
      action:
        debug: 
